enable_checkpointing: true
default_root_dir: results
gradient_clip_val: 0
gradient_clip_algorithm: norm
num_nodes: 1
devices: [0]
enable_progress_bar: true
overfit_batches: 0.0
check_val_every_n_epoch: 1 # Don't validate before extracting features.
fast_dev_run: false
accumulate_grad_batches: 1
max_epochs: 1
min_epochs: null
max_steps: -1
min_steps: null
max_time: null
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
limit_predict_batches: 1.0
val_check_interval: 1.0 # Don't validate before extracting features.
log_every_n_steps: 1
accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
strategy: auto
sync_batchnorm: false
precision: 16
enable_model_summary: true
num_sanity_val_steps: 0
profiler: null
benchmark: false
deterministic: false
reload_dataloaders_every_n_epochs: 0
detect_anomaly: false
plugins: null